version: "3"
services:
  # Collector
  # collector:
  #   image: otel/opentelemetry-collector:latest
  #   command: ["--config=/conf/collector.dev.yaml", "--log-level=DEBUG"]
  #   volumes:
  #     - ./collector.dev.yaml:/conf/collector.dev.yaml
  #   ports:
  #     - "9464:9464"
  #     - "55680:55680"
  #     - "55681:55681"
  #   depends_on:
  #     - zipkin-all-in-one

  # # Zipkin
  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   ports:
  #     - "9411:9411"

  # Step Functions Local
  step-functions:
    image: amazon/aws-stepfunctions-local:latest
    ports:
      - "8083"
    environment:
      - AWS_ACCOUNT_ID=012345678901
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - LAMBDA_ENDPOINT=http://host.docker.internal:3001