version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-functions-debug"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-losv468h9xqj"
s3_prefix = "step-functions-debug"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
