AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  step-functions-debug

  Sample SAM Template for step-functions-debug

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
        StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
        StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction
      Tracing: 
        Enabled: True

  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/StockChecker/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers: 
        - arn:aws:lambda:us-east-1:858558912218:layer:otel-collector:3
        - arn:aws:lambda:us-east-1:858558912218:layer:otel-node:2
      Environment:
        Variables:
          OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
          AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler

  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/StockSeller/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/StockBuyer/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

  # TriggerFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/Trigger/
  #     Handler: app.lambdaHandler
  #     Runtime: nodejs14.x
  #     Layers: 
  #       - arn:aws:lambda:us-east-1:858558912218:layer:otel-collector:3
  #       - arn:aws:lambda:us-east-1:858558912218:layer:otel-node:1
  #     Environment:
  #       Variables:
  #         STATE_MACHINE_ARN: !Ref StockTradingStateMachine
  #         OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
  #         AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StockTradingStateMachineArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref StockTradingStateMachine
  StockTradingStateMachineRole:
    Description: "IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates"
    Value: !GetAtt StockTradingStateMachineRole.Arn
